- d2l-sequence-viewer.html
- lang/en.json
- locales.json
Instead of using a span to represent the back to content home link at the top, we now use d2l-link elements.
> Change element type from span to d2l-link

- d2l-sequence-viewer.html
This is part one of the fix. 
We'll send a `back-click` event from the EoL `I'm Done` button to signal the viewer to navigate to the `returnUrl`. We don't have access to it on the EoL page anymore since everything goes through the router and the router only passes href and token.
> Listen for back-click event

- d2l-sequence-viewer.html
As it is now, when we launch something from the sequenceLauncher the `back to content` link in the ASV will point to `document.referrer` which is the src of the iFrame that holds the sequenceLauncher and not actually content home. [This is all assuming no returnUrl is provided]. 
In order to fix this, we can give priority to defaultReturnLink (which points to content home - or lessons home if it's turned on).
> Prioritize default return url over document referrer

- d2l-sequence-viewer.html
- package-lock.json
The problem: 
The page loads, `getReturnUrl` gets called, entity is null and `returnUrl` is set to `document.referrer` because everything else is undefined. 
When entity loads and `getReturnUrl` gets called again, it is the first item on the list and it has the value of `document.referrer` so we get `document.Referrer` no matter what. 
This is essentially a bug we never discovered before because the conditions needed for it were never tested but Gauth found this bug the other day. 
EDIT: NEW SOLUTION
Add a new parameter called `backToContentLink` so that we don't use the value of `returnUrl` to determine its own value. So instead of having a function to compute `returnUrl` we have a function to computer `backToContentLink`.
> fix logic in _getReturnUrl

- d2l-sequence-viewer.html
- package-lock.json
PART 2 of 2. PART 1: https://github.com/BrightspaceHypermediaComponents/sequences/pull/76
Instead of passing the title of the page as the `state` to `pushState`, we pass in the `href` of the current activity and in the `popstate` event listener, we use the `href` to navigate the user to their previous activity.
> Add popstate listener and fix pushstate

- components/sequence-viewer-header.js
Shortens min length of topbar so that next and previous buttons are not cut off on mobile devices.
> Shortens min length of topbar

- package.json
This makes dep consistent, which otherwise can sometimes cause nested duplicates in BSI.
> Make d2l-sequences dependency consistent 

- package-lock.json
- package.json
The new version has changes to support embedded scorm.
For reference:
sequence release: https://github.com/BrightspaceHypermediaComponents/sequences/releases/tag/v1.3.9
PR that was merged: https://github.com/BrightspaceHypermediaComponents/sequences/pull/149
> Update version of d2l-sequences.

- components/sequence-viewer-header.js
- d2l-sequence-viewer.js
- test/d2l-sequence-viewer.html
- test/sequence-viewer-header.html
- Added telemetry to the header nav buttons. They will log events for "previous" and "next"
- Fixed an unrelated issue with `sideBarClosed` being called on every single click
- Completely refactored the header test suite.
> US105244 - Add telemetry to header nav buttons

- d2l-sequence-viewer.js
Updated the _setModuleProperties function so that instead of going to the very top entity, it will only go up to the sequence root. This fixes the situation where the sequence root is not the same as the root entity. When the correct properties are passed to the sequence navigator, we can properly track progress.
> Updated the properties selector logic to grab to root element

- d2l-sequence-viewer.js
- test/d2l-sequence-viewer.html
Setting single topic view to true when the page loads and we do not have an entity. This leads to a better user experience, where elements load in, as opposed to loading out.
> Default to single topic view before the entity is loaded

- components/sequence-viewer-header.js
- d2l-sequence-viewer.js
- helpers/performance-helper.js
- helpers/telemetry-helper.js
- test/d2l-sequence-viewer.html
- test/sequence-viewer-header.html
Note: there is no new behaviour in this pr, just a change in implementation.
After working on the first pass of the telemetry and thinking about what will need to be done for the future tickets (especially if we move all of sequences into 1 single repo) I realized that the current approach was not super sustainable. What was happening was I was creating a new client for every single event. Right now that's not the end of the world but when there are going to be lots of events this will be really wasteful. Also this helps clean up the code and make testing actually much easier.
I will highlight the important changes, but basically the new approach is that the SeqViewer will still receive the endpoint the same way, but it will instantiate one single client and share that with it's children …
> Make the TelemetryHelper not static

- d2l-sequence-viewer.js
- Log a telemetry event when the user presses the back button in the browser.
Sample payload:
> US105246: Log telemetry event on back button press

- d2l-sequence-viewer.js
- Add telemetry tracking when the user clicks the End of Lesson nav button.
Sample payload: Note that this event says end of `unit` but I changed it to lesson. It takes a while to get this running in bsi and I didn't want to go through the process again just to see a text change.
> US105249: add telemetry tracking for end of lesson click

- package-lock.json
Left out a `^` that should have been there.
> Fixin pdf viewer semver

- d2l-sequence-viewer.js
Sequence viewer uses nested iframes. 
One problem was the outer iframe height was extending beyond the height of the actual screen. This will normally just give you a double scroll bar, but there are issues with some devices (iOS) where scrolling the inner iframe will not scroll the outer iframe. Compound this issue with newer iPhones which have an unsafe top and bottom area which are used as part of the viewheight calculation (which this component heavily relies on...) and lots of content (around 70px worth) will be cutoff the bottom.
This pr changes this to just manually set the height using the `window.innerHeight` property which seems to ignore those unsafe areas, and works well in all other browsers as well.
Example screenshot of a few different devices scrolling to the bottom of the …
> DE37107: fix content being cutoff in sequence viewer

- d2l-sequence-viewer.js
Apparently the last fix was not sufficient. 
Basically, iOS has trouble detecting scrolling touches on inner scrollable items. So you need to tell the containing divs to allow those scrolling touches.
Either it appeared to have work on my simulator but not real devices, or there is a difference depending on the iOS version. Regardless, this appears to make scrolling work on iOS 12, and this should be fine on newer versions.
> DE37477: Another attempt at scrolling on iOS

- d2l-sequence-viewer.js
I removed a few CSS properties that were likely added when trying to get the iOS Quizzes/Survey situation to work, but it looks like those properties only caused more problems and removing them seems to work. I added a background colour in a few of these screenshots while testing to help verify my changes.
**Windows Chrome:**
**MacOS Safari:**
**iOS Safari HTML Doc:**
**iOS Safari Quiz:**
> Remove double scroll bar when viewing HTML docs

- .dependabot/config.yml
- package-lock.json
This PR updates a bunch of dependencies and enables dependabot for security updates
the changes to package-lock are a result of `npm audit fix`
> Enabling dependabot

- components/d2l-sequence-viewer-sidebar.js
- d2l-sequence-viewer.js
Header in navigation pane now utilizes `d2l-lesson-header` to match [design specs](https://xd.adobe.com/view/e16d4c3f-77f8-4632-6a01-a98beb7c5072-975c/screen/2fc07bba-3928-4455-a3c2-589589994d8d/Specs-Navigation-Button-States).
This PR does not include the performance changes that relate to this specific [rally ticket](https://rally1.rallydev.com/#/289692574792d/detail/userstory/391840650276?fdp=true). Those changes will be in a sequences PR.
> imcdonald/us116703 swap navigation header for d2l-lesson-header component

- components/d2l-sequence-viewer-iterator.js
- components/d2l-sequence-viewer-new-content-alert.js
- components/d2l-sequence-viewer-sidebar.js
- components/sequence-viewer-header.js
- d2l-sequence-viewer.js
This pr redesigns the sidebar positioning and the header for LX.
Changes:
- The sidebar is always at the left side of the screen.
- The sidebar will fill 1/3 of the screen width on higher resolutions, until maxed out at 570px.
- The content will center itself inthe remaining 2/3 of the screen (or more when sidebar is maxed out)
- The header buttons have shifted, and the left content will animate as the sidebar slides out. The move separately, but this design was approved.
The Back to Content text will hide at lower resolutions
> Redesign header and sidebar position

- components/d2l-sequence-viewer-sidebar.js
- d2l-sequence-viewer.js
Adding end of unit link back into side-nav.
There will be another [PR in sequences](https://github.com/BrightspaceHypermediaComponents/sequences/pull/236) modifying styles.
See [rally ticket.](https://rally1.rallydev.com/#/289692574792d/detail/userstory/395635592416?fdp=true)
> Add end of unit link to side-nav

- components/sequence-viewer-header.js
- d2l-sequence-viewer.js
Previously it was possible for the right-side nav arrows to be "hidden" behind the left side of the header, even though it was visible. The header is setup this way because the left side can grow and shrink on top of the right side.
I used z-index to allow the left side to properly overlap. However, this caused a problem where certain resolutions allowed it to be slightly on top if the arrows preventing the user from clicking them.
This pr moves the z-index off the "outer" left header and onto the "inner" left header - the part that actually grows and shrinks to overlap. The appearance is still the same, but having the z-index be on the child will not interfere with click events on the parent siblings.
I also adjusted the pixel breakpoints for some minor styling adjustments.
> Fix nav arrows not being interact-able on small devices

- components/sequence-viewer-header.js
- d2l-sequence-viewer.js
For some reason, lower versions of iOS started to have issues with the hamburger button. I modified the structure to move it back to spot where it originally worked before this pr: https://github.com/Brightspace/d2l-sequence-viewer/pull/289/files
I don't know if this will actually fix the issue on iOS as we don't have a great way to repro that specific iOS version with these changes. But based on the fact that it seems like it worked before that pr, it should work and this is harmless if it doesn't fix it.
I also fixed an issue where the header was broken on small screens while in single topic view.
> Hopefully fix header for iOS and single topic view
