demo/index.html

I know we're no longer striving to keep the demo page up-to-date with development. But I just wanted to fix this tiny thing so that I can play around with the landing page design while waiting for UMD stuff to be fixed.

give demo page correct font

---

README.md
package-lock.json

I added a line to the README with a link to where the demo on the local web server would appear.

Fix readme local demo

---

d2l-sequence-viewer.html
package-lock.json

https://rally1.rallydev.com/#/15545269080d/detail/userstory/253532195272
Making sure the nav bar does not hide when the user clicks another window

US100300 TA128382 Don't hide nav bar

---

index.html
package-lock.json

I think this is what is messing up @lawong-d2l

remove systemjs references

---

d2l-sequence-viewer.html
lang/en.json
locales.json
package-lock.json
test/d2l-sequence-viewer.html

The button at the top left will not take the user back to the page where they launched the ASV.

Us100671 ta128651 fix back to home button

---

bower.json
d2l-sequence-viewer.html

Removing code that wasn't deleted as a part of the Back to Content Home change

Removing unused org and module requests, that caused an infinite loop

---

components/sequence-viewer-header.html
d2l-sequence-viewer.html

related PR: https://github.com/BrightspaceHypermediaComponents/sequences/pull/53

change focus to viewer after iterating

---

d2l-sequence-viewer.html
package-lock.json

If returnUrl and document.referrer are both null, the back to home button should take us to content home by default. This link is provided by the siren entity.

Fetch default-return-url from entity

---

bower.json
d2l-sequence-viewer.html

See [this](https://github.com/Brightspace/polymer-frau-jwt/pull/1) for more information about polymer-frau-jwt.

Use polymer-frau-jwt to auto refresh jwt tokens before they expire

---

d2l-sequence-viewer.html
package-lock.json

When the hamburger icon is pressed focus should be on the first element (lesson header) of the nav menu)

Set focus to lesson header when hamburger icon is clicked / entered

---

d2l-sequence-viewer.html
package-lock.json
package.json

adding a watch script
our links.  also adding a watch scriptt

Removing tabindex

---

package-lock.json
package.json

Bumping version to 0.0.50

---

components/sequence-viewer-header.js
demo/index.html
package-lock.json
package.json

https://github.com/BrightspaceHypermediaComponents/sequences/pull/86

Pass next and previous endpoints for a given content topic to iterator

---

d2l-sequence-viewer.js

add overflow for sidebar so that scrollbar for the slide-out menu is

---

components/sequence-viewer-header.js
d2l-sequence-viewer.js
package-lock.json

Addresses issues:
- Immersive navbar: There should be 30px between hamburger menu and edge of page
- Immersive navbar: There should be 24px between the separator and the "back" control
Also added "is-sidebar" to help with functionality in d2l-sequence-navigator.

Second Set of Design Review Styling Changes

---

d2l-sequence-viewer.js
package-lock.json

- Widens sidebar to 405px in total (including padding)
- Makes sure that the sidebar does not extend off of the screen on resolutions with widths less than 405px
- Lines up `#sidebar` with hamburger menu button
2nd Commit:
- Sequence header does not receive focus when hamburger menu is clicked.

Widen sidebar

---

components/sequence-viewer-header.js
package-lock.json

Previously it was being only seen as an h2

Changing the title of the page to a h1 tag

---

d2l-sequence-viewer.js
test/d2l-sequence-viewer.html

bug fix for side nav

---

d2l-sequence-viewer.js
test/d2l-sequence-viewer.html

also removed update status since the api is going to change

fetching module entity and bug fix for UI 

---

d2l-sequence-viewer.js
package-lock.json
package.json

May need tests?
Will also need to bump `d2l-sequence-navigator`
[Related `d2l-sequence-navigator` PR](https://github.com/BrightspaceHypermediaComponents/d2l-sequence-navigator/pull/167)

Pass module entity properties to sequence navigator

---

d2l-sequence-viewer.js
demo/data/unit1.json

Very wip right now. Getting eyeballs on this to see if I'm doing anything wack.

Getting the right index and course name

---

package-lock.json
package.json

This brings in the 20.19.08 translations for the sequence-navigator

Sequence Nav translations

---

d2l-sequence-viewer.js

Turns out empty objects are not falsy

DE35541 Properly check if _moduleProperties is not set

---

d2l-sequence-viewer.js
package.json

This brings in commits from the following PRs (ignoring version bumps)
https://github.com/Brightspace/d2l-sequence-viewer/pull/193
https://github.com/Brightspace/d2l-sequence-viewer/pull/195
https://github.com/Brightspace/d2l-sequence-viewer/pull/196

cbe googledrive hotfix

---

components/sequence-viewer-header.js
d2l-sequence-viewer.js
test/d2l-sequence-viewer.html
test/sequence-viewer-header.html

Added telemetry tracking to the back to content button.

add telemetry tracking for the back to content button

---

package-lock.json

Bump sequences

---

package-lock.json

DE36022: bump sequence navigator

---

package-lock.json

Pulling in Phil's changes for DE34532 https://github.com/BrightspaceHypermediaComponents/sequences/pull/168

bumping sequences

---

package-lock.json

Bringing in this PR https://github.com/BrightspaceHypermediaComponents/sequences/pull/175

DE37295 - bump sequences

---

components/d2l-sequence-viewer-new-content-alert.js

anotha one

---

d2l-sequence-viewer.js

add overflow auto to viewframe for ios scrolling

---

d2l-sequence-viewer.js

This is bringing PR #252, PR #253 and PR #254 to 20.20.1 for DE37477

Backport DE37477

---

d2l-sequence-viewer.serge.json

This is needed to get Danish and France French translations

adding French and Danish to serge

---

d2l-sequence-viewer.js
package-lock.json
test/d2l-sequence-viewer.html

Requires [this sequences PR](https://github.com/BrightspaceHypermediaComponents/sequences/pull/181)

DE37821 flexbox and animations

---

package-lock.json

sequences 1.5.8

---

package-lock.json

Bringing in updated translations and this "DE38306 - This looks for the embed link that will be in the API" https://github.com/BrightspaceHypermediaComponents/sequences/pull/212

updating sequences

---

components/d2l-sequence-viewer-sidebar.js
d2l-sequence-viewer.js
demo/data/l1-m2-activity2.json
demo/index.html
package-lock.json
package.json
test/d2l-sequence-viewer.html

This is still a WIP as the design is still changing. Will update as we go, but in general the approach I've taken on this can be reviewed.
Required `sequences` pr: https://github.com/BrightspaceHypermediaComponents/sequences/pull/229

Update sidebar to use sequences 2.0

---

components/sequence-viewer-header.js

Adjust conditional HTML so that the toggle is not shown when in single topic view.

Don't show menu toggle when viewing single topic
